name: On default

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: 'npm'

    - name: Install, Build and Test
      run: |
        echo "\$ npm install --global npm"
        npm install --global npm

        echo "\$ npm ci --ignore-scripts"
        npm ci --ignore-scripts

        echo "\$ npm install react --no-save --no-package-lock"
        npm install react --no-save --no-package-lock

        echo "\$ npm ls --depth=0"
        npm ls --depth=0

        echo "\$ npm run build"
        npm run build

        echo "\$ npm test"
        npm test
      env:
        CI: true
